-- 한 줄 주석
/* 범위 주석 */


/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER KH_LDH IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_LDH;

ALTER USER KH_LDH DEFAULT TABLESPACE 
USERS QUOTA 20M ON USERS;