-- 한 줄 주석
/* 범위 주석 */


/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER KH_LDH IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_LDH;

ALTER USER KH_LDH DEFAULT TABLESPACE 
USERS QUOTA 50M ON USERS;



/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER REPET_LDH IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO REPET_LDH;

ALTER USER REPET_LDH DEFAULT TABLESPACE USERS QUOTA 500M ON USERS;



/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_PLKLJ IDENTIFIED BY PLKLJ1234;

GRANT RESOURCE, CONNECT TO KH_PLKLJ;

ALTER USER KH_PLKLJ DEFAULT TABLESPACE USERS QUOTA 500M ON USERS;
