SELECT 
*
FROM
MEMBER;


SELECT
*
FROM
NOTICE;

SELECT
*
FROM
QUESTION;



SELECT 
    QUESTION_NO,
    QUESTION_CONTENT,
    QUESTION_ANSWER
FROM (
    SELECT 
        QUESTION_NO,
        QUESTION_CONTENT,
        QUESTION_ANSWER,
        QUESTION_DATE
    FROM 
        "QUESTION"
    ORDER BY 
        QUESTION_DATE DESC
)
WHERE ROWNUM <= 5;


UPDATE QUESTION
SET QUESTION_ANSWER = '이것은 테스트 답변입니다.'
WHERE QUESTION_NO = 13;

UPDATE QUESTION
SET QUESTION_ANSWER = '배송 관련 안내입니다.'
WHERE QUESTION_NO = 12;

UPDATE QUESTION
SET QUESTION_ANSWER = '테스트 답변 1입니다.'
WHERE QUESTION_NO = 14;

UPDATE QUESTION
SET QUESTION_ANSWER = '테스트 답변 2입니다.'
WHERE QUESTION_NO = 15;

UPDATE QUESTION
SET QUESTION_ANSWER = '테스트 답변 3입니다.'
WHERE QUESTION_NO = 16;


-- 데이터 삽입
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '서비스 점검 안내', '서비스 점검으로 인해 일시적인 접속 불가가 발생할 예정입니다.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '신규 기능 업데이트', '신규 기능 추가로 더욱 편리한 서비스를 이용하실 수 있습니다.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '이용약관 변경 안내', '이용약관이 2024년 11월 20일부로 변경됩니다. 상세 내용은 공지사항을 참조하세요.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '추석 연휴 휴무 안내', '다가오는 추석 연휴로 인해 고객센터가 휴무일을 가집니다.', SYSDATE, 'Y');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '시스템 업데이트', '2024년 12월 1일에 시스템 업데이트가 예정되어 있습니다. 불편을 드려 죄송합니다.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '긴급 보안 업데이트', '보안 강화를 위해 긴급 업데이트가 진행될 예정입니다. 자세한 사항은 공지사항을 참조하세요.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '서비스 중단 안내', '서버 점검으로 인해 서비스가 2024년 11월 25일에 일시적으로 중단될 예정입니다.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '고객 이벤트 안내', '11월 특별 고객 감사 이벤트가 진행됩니다. 자세한 내용은 홈페이지를 확인하세요.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '회원 정책 변경', '회원 등급 정책이 2024년 12월 1일부로 개정됩니다. 변경 사항을 확인하세요.', SYSDATE, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE, NOTICE_DEL_FL) VALUES
(SEQ_NOTICE_NO.NEXTVAL, '비밀번호 변경 권장', '계정 보안을 위해 비밀번호를 정기적으로 변경해 주세요.', SYSDATE, 'N');



COMMIT;

ROLLBACK;

