


-------------- 세미 프로젝트 DB -------------------------


/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER REPET IDENTIFIED BY RP1234;

GRANT RESOURCE, CONNECT TO REPET;

ALTER USER REPET DEFAULT TABLESPACE USERS QUOTA 500M ON USERS;


CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

DROP SEQUENCE SEQ_MEMBER_NO;



