CREATE TABLE TD_LIST(
	LIST_TITLE  VARCHAR2(30) NOT NULL,
	LIST_DETAIL VARCHAR2(30) NOT NULL,
	LIST_COMPLETE CHAR(1) CHECK (LIST_COMPLETE IN ('Y', 'N')) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TD_LIST.LIST_TITLE     	IS '리스트 제목';
COMMENT ON COLUMN TD_LIST.LIST_DETAIL     IS '리스트 상세내용';
COMMENT ON COLUMN TD_LIST.LIST_COMPLETE   IS '리스트 완료여부';
COMMENT ON COLUMN TD_LIST.ENROLL_DATE 		IS '리스트 완료일';


-- 샘플 데이터 INSERT
INSERT INTO TD_LIST 
VALUES('숙제1', '자바', 'Y', DEFAULT );
INSERT INTO TD_LIST 
VALUES('숙제2', '자바스크립트', 'Y', DEFAULT );
INSERT INTO TD_LIST 
VALUES('숙제3', '디비', 'Y', DEFAULT );


SELECT * FROM TD_LIST
ORDER BY
1;


	SELECT 
			LIST_TITLE,
			LIST_DETAIL,
			LIST_COMPLETE,
			TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') 
			ENROLL_DATE
		FROM
			 TD_LIST;


COMMIT;






