CREATE TABLE TD_LIST(
	LIST_NO     NUMBER CONSTRAINT TD_LIST_PK PRIMARY KEY,
	LIST_TITLE  VARCHAR2(30) NOT NULL,
	LIST_DETAIL VARCHAR2(30) NOT NULL,
	LIST_COMPLETE NUMBER DEFAULT 0,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

ALTER TABLE TD_LIST
ADD CONSTRAINT LIST_COMPLETE_CHECK 
CHECK(LIST_COMPLETE IN (0, 1) );

COMMENT ON COLUMN TD_LIST.LIST_NO     		IS '리스트 번호';
COMMENT ON COLUMN TD_LIST.LIST_TITLE     	IS '리스트 제목';
COMMENT ON COLUMN TD_LIST.LIST_DETAIL     IS '리스트 상세내용';
COMMENT ON COLUMN TD_LIST.LIST_COMPLETE   IS '리스트 완료여부';
COMMENT ON COLUMN TD_LIST.ENROLL_DATE 		IS '리스트 완료일';


CREATE SEQUENCE SEQ_LIST_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TD_LIST 
VALUES(SEQ_LIST_NO.NEXTVAL, '숙제1', '자바', DEFAULT, DEFAULT );
INSERT INTO TD_LIST 
VALUES(SEQ_LIST_NO.NEXTVAL, '숙제2', '자바스크립트', DEFAULT, DEFAULT );
INSERT INTO TD_LIST 
VALUES(SEQ_LIST_NO.NEXTVAL, '숙제3', '디비', DEFAULT, DEFAULT );


SELECT * FROM TD_LIST
ORDER BY
1;


	
DROP TABLE TD_LIST;


COMMIT;


ROLLBACK;

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_LIST_NO;





